// SPDX-License-Identifier: Apache-2.0
//! Cross-module integration tests for the Podman-native architecture pivot.
//!
//! These tests validate the contracts between the generator modules (puzzled)
//! and the consumer binaries (puzzle-hook, puzzle-init) that together
//! implement the Podman-native governance flow:
//!
//!   puzzle-podman → puzzled (generate seccomp + landlock) → Podman/crun
//!     → puzzle-hook (OCI hook, D-Bus) → puzzle-init (Landlock shim)
//!
//! The tests verify:
//! 1. Seccomp profiles generated by puzzled are valid OCI format
//! 2. Landlock rules generated by puzzled can be parsed by puzzle-init's schema
//! 3. Seccomp and Landlock rules are mutually compatible
//! 4. OCI hook annotation contract matches puzzle-podman's output
//! 5. Full flow: profile → generated artifacts → consumer parsing

use std::path::{Path, PathBuf};

use puzzled_types::{
    AgentProfile, BehavioralConfig, EnforcementRequirements, FailMode, FilesystemRules,
    NetworkConfig, NetworkMode, ResourceLimits, SeccompMode,
};

// ═══════════════════════════════════════════════════════════════════════════
// 1. Seccomp ↔ Landlock compatibility
// ═══════════════════════════════════════════════════════════════════════════

/// The seccomp profile must explicitly ALLOW Landlock syscalls so that
/// puzzle-init can call landlock_restrict_self() inside the container.
/// If seccomp blocks these, Landlock enforcement silently fails.
#[test]
fn seccomp_allows_landlock_syscalls() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let allow_rule = profile
        .syscalls
        .iter()
        .find(|r| r.action == "SCMP_ACT_ALLOW")
        .expect("profile must have an ALLOW rule for Landlock syscalls");

    for syscall in &[
        "landlock_create_ruleset",
        "landlock_add_rule",
        "landlock_restrict_self",
    ] {
        assert!(
            allow_rule.names.contains(&syscall.to_string()),
            "ALLOW rule must include {syscall}"
        );
    }
}

/// Landlock syscalls must NOT appear in the DENY list.
/// This would be a fatal conflict — Landlock enforcement would kill the process.
#[test]
fn seccomp_deny_list_does_not_block_landlock() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let landlock_syscalls = [
        "landlock_create_ruleset",
        "landlock_add_rule",
        "landlock_restrict_self",
    ];

    for rule in &profile.syscalls {
        if rule.action == "SCMP_ACT_KILL_PROCESS" {
            for syscall in &landlock_syscalls {
                assert!(
                    !rule.names.contains(&syscall.to_string()),
                    "KILL_PROCESS rule must NOT contain {syscall}"
                );
            }
        }
    }
}

/// The seccomp NOTIFY tier must include execve and connect (minimum for governance).
/// Without these, puzzled cannot gate exec or network in Podman-native mode.
#[test]
fn seccomp_notify_includes_governance_syscalls() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let notify_rule = profile
        .syscalls
        .iter()
        .find(|r| r.action == "SCMP_ACT_NOTIFY")
        .expect("profile must have NOTIFY rule when include_notify=true");

    for required in &["execve", "execveat", "connect", "bind"] {
        assert!(
            notify_rule.names.contains(&required.to_string()),
            "NOTIFY rule must include {required}"
        );
    }
}

/// NOTIFY rules must include listenerPath pointing to puzzled's socket.
/// Without this, crun cannot send the notification fd to puzzled.
#[test]
fn seccomp_notify_has_listener_path() {
    let socket = "/run/puzzled/seccomp-notify.sock";
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "branch-42",
        Path::new(socket),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    assert_eq!(
        profile.listener_path.as_deref(),
        Some(socket),
        "listenerPath must point to puzzled's socket"
    );
}

/// listenerMetadata must contain the branch_id so puzzled can route
/// notifications to the correct branch handler.
#[test]
fn seccomp_listener_metadata_contains_branch_id() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "my-branch-abc",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let metadata = profile
        .listener_metadata
        .as_ref()
        .expect("metadata must be set");
    let parsed: serde_json::Value =
        serde_json::from_str(metadata).expect("metadata must be valid JSON");
    assert_eq!(
        parsed["branch_id"].as_str(),
        Some("my-branch-abc"),
        "metadata must contain branch_id"
    );
}

/// Static-only profiles (include_notify=false) must NOT have listener fields.
#[test]
fn seccomp_static_only_has_no_listener() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "branch-static",
        Path::new("/run/puzzled/seccomp.sock"),
        false,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    assert!(profile.listener_path.is_none());
    assert!(profile.listener_metadata.is_none());
    assert!(
        !profile
            .syscalls
            .iter()
            .any(|r| r.action == "SCMP_ACT_NOTIFY"),
        "static-only profile must not have NOTIFY rules"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Landlock rules generator → puzzle-init parser contract
// ═══════════════════════════════════════════════════════════════════════════

/// Rules generated by puzzled must match the JSON schema puzzle-init expects:
/// { abi: String, read: [String], write: [String], exec: [String], allow_refer: bool }
#[test]
fn landlock_rules_match_init_schema() {
    let profile = create_test_profile("standard");
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .expect("generation must succeed");

    let json = serde_json::to_string_pretty(&rules).expect("serialization must succeed");
    let parsed: serde_json::Value = serde_json::from_str(&json).expect("must parse as valid JSON");

    assert_eq!(parsed["abi"].as_str(), Some("V5"));
    assert!(parsed["read"].is_array());
    assert!(parsed["write"].is_array());
    assert!(parsed["exec"].is_array());
    assert!(parsed["allow_refer"].is_boolean());

    let write_paths: Vec<&str> = parsed["write"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    assert!(write_paths.contains(&"/workspace"));
    assert_eq!(
        parsed["allow_refer"].as_bool(),
        Some(profile.allow_symlinks),
    );
}

/// Verify that profile read_allowlist paths appear in generated rules
/// (minus denylisted paths).
#[test]
fn landlock_rules_preserves_read_allowlist() {
    let profile = create_test_profile("standard");
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .expect("generation must succeed");

    for path in &profile.filesystem.read_allowlist {
        let path_str = path.to_string_lossy().to_string();
        if !profile
            .filesystem
            .denylist
            .iter()
            .any(|d| path.starts_with(d))
        {
            assert!(
                rules.read.contains(&path_str),
                "read_allowlist path {path_str} must appear in generated rules"
            );
        }
    }
}

/// Denylisted paths must be excluded from generated rules.
#[test]
fn landlock_rules_excludes_denylisted_paths() {
    let mut profile = create_test_profile("standard");
    profile
        .filesystem
        .denylist
        .push(std::path::PathBuf::from("/etc/shadow"));
    profile
        .filesystem
        .read_allowlist
        .push(std::path::PathBuf::from("/etc/shadow"));

    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    assert!(
        !rules.read.contains(&"/etc/shadow".to_string()),
        "denylisted path must not appear in read rules"
    );
}

/// Standard system paths must be added for basic binary execution.
#[test]
fn landlock_rules_includes_standard_system_paths() {
    let profile = create_restricted_profile();
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    for expected in &[
        "/usr",
        "/lib",
        "/lib64",
        "/etc/ld.so.cache",
        "/etc/ld.so.conf",
    ] {
        assert!(
            rules.read.contains(&expected.to_string()),
            "standard system path {expected} must be in read rules"
        );
    }
}

/// Workspace directory must always be writable regardless of profile.
#[test]
fn landlock_rules_workspace_always_writable() {
    let profile = create_restricted_profile();
    let rules = puzzled::landlock_rules::generate_landlock_rules(
        &profile,
        Path::new("/var/lib/puzzled/branches/br-1/merged"),
    )
    .unwrap();

    assert!(rules
        .write
        .contains(&"/var/lib/puzzled/branches/br-1/merged".to_string()));
}

/// Restricted profile generates minimal write rules — only workspace.
#[test]
fn landlock_rules_restricted_profile_minimal() {
    let profile = create_restricted_profile();
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    assert_eq!(rules.write.len(), 1, "only workspace in write rules");
    assert_eq!(rules.write[0], "/workspace");
}

/// All ABI versions must be representable in the generated JSON.
#[test]
fn landlock_rules_abi_versions_parseable() {
    for abi in &["V1", "V2", "V3", "V4", "V5", "V6"] {
        let json =
            format!(r#"{{"abi": "{abi}", "read": ["/usr"], "write": ["/tmp"], "exec": []}}"#);
        let parsed: serde_json::Value = serde_json::from_str(&json)
            .unwrap_or_else(|e| panic!("ABI version {abi} must be parseable: {e}"));
        assert_eq!(parsed["abi"].as_str(), Some(*abi));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. OCI hook annotation contract
// ═══════════════════════════════════════════════════════════════════════════

/// Annotation keys/values must match the contract between puzzle-podman
/// (producer) and puzzle-hook (consumer).
#[test]
fn oci_hook_recognizes_puzzle_podman_annotations() {
    let state_json = make_oci_state_json(
        "creating",
        Some(12345),
        &[
            ("run.oci.handler", "puzzlepod"),
            ("org.lobstertrap.puzzlepod.branch", "branch-abc-123"),
        ],
    );

    let state: serde_json::Value = serde_json::from_str(&state_json).unwrap();
    let annotations = state["annotations"].as_object().unwrap();

    assert_eq!(
        annotations.get("run.oci.handler").and_then(|v| v.as_str()),
        Some("puzzlepod"),
    );
    assert_eq!(
        annotations
            .get("org.lobstertrap.puzzlepod.branch")
            .and_then(|v| v.as_str()),
        Some("branch-abc-123"),
    );
}

/// Containers without the handler annotation must not trigger the hook.
#[test]
fn oci_hook_skips_non_puzzlepod_containers() {
    let state_json = make_oci_state_json(
        "creating",
        Some(12345),
        &[("some.other.annotation", "value")],
    );

    let state: serde_json::Value = serde_json::from_str(&state_json).unwrap();
    assert!(state["annotations"]
        .as_object()
        .unwrap()
        .get("run.oci.handler")
        .is_none());
}

/// Poststop stage may not have a PID (process already exited).
#[test]
fn oci_state_poststop_no_pid() {
    let state_json = make_oci_state_json(
        "stopped",
        None,
        &[
            ("run.oci.handler", "puzzlepod"),
            ("org.lobstertrap.puzzlepod.branch", "branch-xyz"),
        ],
    );

    let state: serde_json::Value = serde_json::from_str(&state_json).unwrap();
    assert!(state["pid"].is_null());
}

/// OCI state status field must match the expected hook stage values.
#[test]
fn oci_state_status_values_valid() {
    for status in &["creating", "stopped"] {
        let state_json = make_oci_state_json(
            status,
            Some(1234),
            &[
                ("run.oci.handler", "puzzlepod"),
                ("org.lobstertrap.puzzlepod.branch", "branch-1"),
            ],
        );
        let state: serde_json::Value = serde_json::from_str(&state_json).unwrap();
        assert_eq!(state["status"].as_str(), Some(*status));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. File I/O roundtrip
// ═══════════════════════════════════════════════════════════════════════════

/// Generate seccomp profile, write to disk, read back, verify all fields.
#[test]
fn seccomp_profile_write_read_roundtrip() {
    let dir = tempfile::tempdir().unwrap();
    let output_path = dir.path().join("seccomp.json");

    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "roundtrip-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        true,
        SeccompMode::Permissive,
    )
    .unwrap();

    puzzled::seccomp_profile::write_seccomp_profile(&profile, &output_path).unwrap();

    let contents = std::fs::read_to_string(&output_path).unwrap();
    let deserialized: puzzled::seccomp_profile::OciSeccompProfile =
        serde_json::from_str(&contents).unwrap();

    assert_eq!(deserialized.default_action, profile.default_action);
    assert_eq!(deserialized.default_errno_ret, profile.default_errno_ret);
    assert_eq!(deserialized.listener_path, profile.listener_path);
    assert_eq!(deserialized.listener_metadata, profile.listener_metadata);
    assert_eq!(deserialized.architectures, profile.architectures);
    assert_eq!(deserialized.syscalls.len(), profile.syscalls.len());
}

/// Generate landlock rules, write to disk, read back, verify.
#[test]
fn landlock_rules_write_read_roundtrip() {
    let dir = tempfile::tempdir().unwrap();
    let output_path = dir.path().join("landlock.json");

    let profile = create_test_profile("standard");
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    puzzled::landlock_rules::write_landlock_rules(&rules, &output_path).unwrap();

    let contents = std::fs::read_to_string(&output_path).unwrap();
    let parsed: serde_json::Value = serde_json::from_str(&contents).unwrap();

    assert_eq!(parsed["abi"].as_str(), Some("V5"));
    let write_paths: Vec<&str> = parsed["write"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    assert!(write_paths.contains(&"/workspace"));
    assert_eq!(parsed["read"].as_array().unwrap().len(), rules.read.len());
    assert_eq!(parsed["exec"].as_array().unwrap().len(), rules.exec.len());
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. Seccomp deny list completeness
// ═══════════════════════════════════════════════════════════════════════════

/// Critical escape-vector syscalls must be in the KILL_PROCESS tier.
#[test]
fn seccomp_denies_critical_escape_vectors() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let deny_rule = profile
        .syscalls
        .iter()
        .find(|r| r.action == "SCMP_ACT_KILL_PROCESS")
        .expect("must have KILL_PROCESS rule");

    let critical = [
        "ptrace",
        "mount",
        "umount2",
        "setns",
        "unshare",
        "bpf",
        "kexec_load",
        "init_module",
        "finit_module",
        "pivot_root",
        "chroot",
        "io_uring_setup",
        "process_vm_readv",
        "process_vm_writev",
    ];

    for syscall in &critical {
        assert!(
            deny_rule.names.contains(&syscall.to_string()),
            "{syscall} must be in KILL_PROCESS deny list"
        );
    }
}

/// Socket type filtering must block raw sockets.
#[test]
fn seccomp_blocks_raw_sockets() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let socket_rules: Vec<_> = profile
        .syscalls
        .iter()
        .filter(|r| r.action == "SCMP_ACT_ERRNO" && r.names.contains(&"socket".to_string()))
        .collect();

    assert!(socket_rules.len() >= 2, "must block SOCK_RAW + SOCK_PACKET");

    let blocked_values: Vec<u64> = socket_rules
        .iter()
        .filter_map(|r| r.args.as_ref())
        .flat_map(|args| args.iter().map(|a| a.value))
        .collect();

    assert!(blocked_values.contains(&3), "SOCK_RAW (3) must be blocked");
    assert!(
        blocked_values.contains(&10),
        "SOCK_PACKET (10) must be blocked"
    );
}

/// Clone guard adds clone/clone3 to NOTIFY tier.
#[test]
fn seccomp_clone_guard_when_enabled() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        true,
        SeccompMode::Permissive,
    )
    .unwrap();

    let notify = profile
        .syscalls
        .iter()
        .find(|r| r.action == "SCMP_ACT_NOTIFY")
        .unwrap();

    assert!(notify.names.contains(&"clone".to_string()));
    assert!(notify.names.contains(&"clone3".to_string()));
}

#[test]
fn seccomp_no_clone_guard_when_disabled() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    let notify = profile
        .syscalls
        .iter()
        .find(|r| r.action == "SCMP_ACT_NOTIFY")
        .unwrap();

    assert!(!notify.names.contains(&"clone".to_string()));
    assert!(!notify.names.contains(&"clone3".to_string()));
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. Architecture coverage
// ═══════════════════════════════════════════════════════════════════════════

/// Must support both x86_64 and aarch64 per PRD target platforms.
#[test]
fn seccomp_profile_covers_target_architectures() {
    let profile = puzzled::seccomp_profile::generate_seccomp_profile(
        "test-branch",
        Path::new("/run/puzzled/seccomp.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();

    assert!(profile
        .architectures
        .contains(&"SCMP_ARCH_X86_64".to_string()));
    assert!(profile
        .architectures
        .contains(&"SCMP_ARCH_AARCH64".to_string()));
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. Profile-specific rule generation
// ═══════════════════════════════════════════════════════════════════════════

/// Privileged profile generates broader rules than restricted.
#[test]
fn landlock_rules_privileged_broader_than_restricted() {
    let restricted = create_restricted_profile();
    let privileged = create_privileged_profile();

    let r_rules =
        puzzled::landlock_rules::generate_landlock_rules(&restricted, Path::new("/workspace"))
            .unwrap();
    let p_rules =
        puzzled::landlock_rules::generate_landlock_rules(&privileged, Path::new("/workspace"))
            .unwrap();

    assert!(p_rules.read.len() >= r_rules.read.len());
    assert!(p_rules.write.len() >= r_rules.write.len());
}

/// exec_allowlist maps to the exec field in generated rules.
#[test]
fn landlock_rules_exec_matches_profile() {
    let mut profile = create_test_profile("standard");
    profile.exec_allowlist = vec![
        "/usr/bin/python3".to_string(),
        "/usr/bin/git".to_string(),
        "/usr/bin/cargo".to_string(),
    ];

    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    assert_eq!(rules.exec.len(), 3);
    assert!(rules.exec.contains(&"/usr/bin/python3".to_string()));
    assert!(rules.exec.contains(&"/usr/bin/git".to_string()));
    assert!(rules.exec.contains(&"/usr/bin/cargo".to_string()));
}

/// allow_symlinks in profile maps to allow_refer in Landlock rules.
#[test]
fn landlock_rules_allow_refer_from_profile() {
    let mut profile = create_test_profile("standard");
    profile.allow_symlinks = true;
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();
    assert!(
        rules.allow_refer,
        "allow_refer must be true when allow_symlinks=true"
    );

    profile.allow_symlinks = false;
    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();
    assert!(
        !rules.allow_refer,
        "allow_refer must be false when allow_symlinks=false"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 8. Full Podman-native artifact generation flow
// ═══════════════════════════════════════════════════════════════════════════

/// Simulate the complete artifact generation flow:
/// 1. Generate seccomp profile
/// 2. Generate landlock rules
/// 3. Write both to disk
/// 4. Verify both are parseable and cross-compatible
#[test]
fn full_podman_native_artifact_generation() {
    let dir = tempfile::tempdir().unwrap();
    let branch_id = "flow-test-branch-42";
    let branch_dir = dir.path().join(branch_id);
    std::fs::create_dir_all(&branch_dir).unwrap();

    let profile = create_test_profile("standard");

    // Generate seccomp profile
    let seccomp = puzzled::seccomp_profile::generate_seccomp_profile(
        branch_id,
        Path::new("/run/puzzled/seccomp-notify.sock"),
        true,
        false,
        SeccompMode::Permissive,
    )
    .unwrap();
    let seccomp_path = branch_dir.join("seccomp.json");
    puzzled::seccomp_profile::write_seccomp_profile(&seccomp, &seccomp_path).unwrap();

    // Generate landlock rules
    let workspace = branch_dir.join("merged");
    std::fs::create_dir_all(&workspace).unwrap();
    let landlock = puzzled::landlock_rules::generate_landlock_rules(&profile, &workspace).unwrap();
    let landlock_path = branch_dir.join("landlock.json");
    puzzled::landlock_rules::write_landlock_rules(&landlock, &landlock_path).unwrap();

    // Verify both files exist and are valid JSON
    assert!(seccomp_path.exists());
    assert!(landlock_path.exists());

    let seccomp_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&seccomp_path).unwrap()).unwrap();
    let landlock_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&landlock_path).unwrap()).unwrap();

    // Seccomp must allow Landlock syscalls
    let allows: Vec<&str> = seccomp_json["syscalls"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r["action"].as_str() == Some("SCMP_ACT_ALLOW"))
        .flat_map(|r| {
            r["names"]
                .as_array()
                .unwrap()
                .iter()
                .filter_map(|n| n.as_str())
        })
        .collect();
    assert!(allows.contains(&"landlock_create_ruleset"));

    // Seccomp must NOTIFY on execve
    let notifies: Vec<&str> = seccomp_json["syscalls"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r["action"].as_str() == Some("SCMP_ACT_NOTIFY"))
        .flat_map(|r| {
            r["names"]
                .as_array()
                .unwrap()
                .iter()
                .filter_map(|n| n.as_str())
        })
        .collect();
    assert!(notifies.contains(&"execve"));

    // Landlock workspace must be writable
    let writes: Vec<&str> = landlock_json["write"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    assert!(writes.iter().any(|p| p.contains("merged")));

    // listenerMetadata branch_id must match
    let metadata: serde_json::Value =
        serde_json::from_str(seccomp_json["listenerMetadata"].as_str().unwrap()).unwrap();
    assert_eq!(metadata["branch_id"].as_str(), Some(branch_id));
}

// ═══════════════════════════════════════════════════════════════════════════
// 9. J81: read_denylist / write_denylist filtering
// ═══════════════════════════════════════════════════════════════════════════

/// J81: Paths in read_denylist must be excluded from generated Landlock read rules.
#[test]
fn j81_landlock_rules_excludes_read_denylist() {
    let mut profile = create_test_profile("denylist-test");
    profile.filesystem.read_allowlist = vec![
        PathBuf::from("/usr"),
        PathBuf::from("/proc/kcore"),
        PathBuf::from("/sys/firmware"),
    ];
    // J81: read_denylist should filter read paths independently of the general denylist
    profile.filesystem.read_denylist =
        vec![PathBuf::from("/proc/kcore"), PathBuf::from("/sys/firmware")];
    // General denylist is empty — only read_denylist should apply
    profile.filesystem.denylist = vec![];

    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    assert!(
        rules.read.contains(&"/usr".to_string()),
        "J81: /usr should be in read rules (not in read_denylist)"
    );
    assert!(
        !rules.read.contains(&"/proc/kcore".to_string()),
        "J81: /proc/kcore must be excluded by read_denylist"
    );
    assert!(
        !rules.read.contains(&"/sys/firmware".to_string()),
        "J81: /sys/firmware must be excluded by read_denylist"
    );
}

/// J81: Paths in write_denylist must be excluded from generated Landlock write rules.
#[test]
fn j81_landlock_rules_excludes_write_denylist() {
    let mut profile = create_test_profile("write-denylist-test");
    profile.filesystem.write_allowlist = vec![PathBuf::from("/tmp"), PathBuf::from("/boot")];
    profile.filesystem.write_denylist = vec![PathBuf::from("/boot")];
    profile.filesystem.denylist = vec![];

    let rules = puzzled::landlock_rules::generate_landlock_rules(&profile, Path::new("/workspace"))
        .unwrap();

    assert!(
        rules.write.contains(&"/tmp".to_string()),
        "J81: /tmp should be in write rules (not in write_denylist)"
    );
    assert!(
        !rules.write.contains(&"/boot".to_string()),
        "J81: /boot must be excluded by write_denylist"
    );
    // Workspace is always included regardless of denylists
    assert!(
        rules.write.contains(&"/workspace".to_string()),
        "J81: workspace must always be writable"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════

fn create_test_profile(name: &str) -> AgentProfile {
    AgentProfile {
        name: name.to_string(),
        description: format!("Test profile: {name}"),
        filesystem: FilesystemRules {
            read_allowlist: vec![PathBuf::from("/usr"), PathBuf::from("/tmp")],
            write_allowlist: vec![PathBuf::from("/tmp")],
            denylist: vec![PathBuf::from("/etc/shadow"), PathBuf::from("/root")],
            read_denylist: vec![],
            write_denylist: vec![],
        },
        exec_allowlist: vec!["/usr/bin/python3".to_string(), "/usr/bin/cat".to_string()],
        exec_denylist: vec!["/usr/bin/rm".to_string()],
        resource_limits: ResourceLimits::default(),
        network: NetworkConfig {
            mode: NetworkMode::Gated,
            allowed_domains: vec!["example.com".to_string()],
            data_residency: None,
            dlp_rules_path: None,
        },
        behavioral: BehavioralConfig::default(),
        fail_mode: FailMode::FailClosed,
        capabilities: vec![],
        enforcement: EnforcementRequirements::default(),
        seccomp_mode: SeccompMode::default(),
        allow_symlinks: false,
        allow_exec_overlay: false,
        credentials: None,
        extends: None,
    }
}

fn create_restricted_profile() -> AgentProfile {
    AgentProfile {
        name: "test-restricted".to_string(),
        description: "Restricted test profile".to_string(),
        filesystem: FilesystemRules {
            read_allowlist: vec![],
            write_allowlist: vec![],
            denylist: vec![],
            read_denylist: vec![],
            write_denylist: vec![],
        },
        exec_allowlist: vec![],
        exec_denylist: vec![],
        resource_limits: ResourceLimits::default(),
        network: NetworkConfig {
            mode: NetworkMode::Blocked,
            allowed_domains: vec![],
            data_residency: None,
            dlp_rules_path: None,
        },
        behavioral: BehavioralConfig::default(),
        fail_mode: FailMode::FailClosed,
        capabilities: vec![],
        enforcement: EnforcementRequirements::default(),
        seccomp_mode: SeccompMode::default(),
        allow_symlinks: false,
        allow_exec_overlay: false,
        credentials: None,
        extends: None,
    }
}

fn create_privileged_profile() -> AgentProfile {
    AgentProfile {
        name: "test-privileged".to_string(),
        description: "Privileged test profile".to_string(),
        filesystem: FilesystemRules {
            read_allowlist: vec![PathBuf::from("/"), PathBuf::from("/usr")],
            write_allowlist: vec![PathBuf::from("/tmp"), PathBuf::from("/workspace")],
            denylist: vec![],
            read_denylist: vec![],
            write_denylist: vec![],
        },
        exec_allowlist: vec!["/usr/bin/*".to_string(), "/usr/local/bin/*".to_string()],
        exec_denylist: vec![],
        resource_limits: ResourceLimits::default(),
        network: NetworkConfig {
            mode: NetworkMode::Monitored,
            allowed_domains: vec!["*".to_string()],
            data_residency: None,
            dlp_rules_path: None,
        },
        behavioral: BehavioralConfig::default(),
        fail_mode: FailMode::FailClosed,
        capabilities: vec![],
        enforcement: EnforcementRequirements::default(),
        seccomp_mode: SeccompMode::default(),
        allow_symlinks: true,
        allow_exec_overlay: true,
        credentials: None,
        extends: None,
    }
}

fn make_oci_state_json(status: &str, pid: Option<u32>, annotations: &[(&str, &str)]) -> String {
    let pid_field = match pid {
        Some(p) => format!("{p}"),
        None => "null".to_string(),
    };
    let ann_entries: Vec<String> = annotations
        .iter()
        .map(|(k, v)| format!(r#""{k}": "{v}""#))
        .collect();

    format!(
        r#"{{
  "ociVersion": "1.0.2",
  "id": "test-container-001",
  "status": "{status}",
  "pid": {pid_field},
  "bundle": "/run/containers/storage/overlay-containers/abc/userdata",
  "annotations": {{ {ann} }}
}}"#,
        ann = ann_entries.join(", ")
    )
}

// ═══════════════════════════════════════════════════════════════════════════
// L60: puzzle-podman symlink resolution for MERGED_DIR/SECCOMP_PATH/LANDLOCK_PATH
// ═══════════════════════════════════════════════════════════════════════════

/// L60: puzzle-podman must resolve symlinks with `readlink -f` for MERGED_DIR,
/// SECCOMP_PATH, and LANDLOCK_PATH to prevent symlink-based path traversal.
/// A symlink like /var/lib/puzzled/branches/evil/merged -> /etc/ would pass
/// the textual prefix check but point outside the allowed directory.
#[test]
fn l60_puzzle_podman_resolves_symlinks_for_paths() {
    let source = include_str!("../../../podman/puzzle-podman");

    // MERGED_DIR must have readlink -f resolution
    assert!(
        source.contains("MERGED_DIR_REAL=\"$(readlink -f"),
        "L60: puzzle-podman must resolve MERGED_DIR symlinks with readlink -f"
    );

    // SECCOMP_PATH must have readlink -f resolution
    assert!(
        source.contains("SECCOMP_PATH_REAL=\"$(readlink -f"),
        "L60: puzzle-podman must resolve SECCOMP_PATH symlinks with readlink -f"
    );

    // LANDLOCK_PATH must have readlink -f resolution
    assert!(
        source.contains("LANDLOCK_PATH_REAL=\"$(readlink -f"),
        "L60: puzzle-podman must resolve LANDLOCK_PATH symlinks with readlink -f"
    );
}
