#!/bin/bash
# dev-setup.sh — Set up and run puzzled for development/testing
#
# Usage (inside Lima VM):
#   sudo scripts/dev-setup.sh setup     # Create dirs, install config/profiles/policies
#   sudo scripts/dev-setup.sh start     # Start puzzled in foreground (Ctrl+C to stop)
#   sudo scripts/dev-setup.sh startbg   # Start puzzled in background
#   sudo scripts/dev-setup.sh stop      # Stop background puzzled
#   sudo scripts/dev-setup.sh status    # Check if puzzled is running
#   sudo scripts/dev-setup.sh logs      # Tail puzzled log (background mode)
#   sudo scripts/dev-setup.sh clean     # Remove all runtime state (branches, WAL, etc.)
#   sudo scripts/dev-setup.sh all       # setup + build + start in foreground
#
# Prerequisites:
#   - Linux (Fedora 42+ / RHEL 10+ / Lima VM)
#   - Rust toolchain installed
#   - Run as root (sudo)

set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Binaries (release build for realistic performance)
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-/var/tmp/puzzlepod-target}"
PUZZLED_BIN="$CARGO_TARGET_DIR/release/puzzled"
[ -x "$PUZZLED_BIN" ] || PUZZLED_BIN="$REPO_DIR/target/release/puzzled"
PUZZLECTL_BIN="$CARGO_TARGET_DIR/release/puzzlectl"
[ -x "$PUZZLECTL_BIN" ] || PUZZLECTL_BIN="$REPO_DIR/target/release/puzzlectl"

# Directories
CONF_DIR="/etc/puzzled"
CONF_FILE="$CONF_DIR/puzzled.conf"
PROFILES_DIR="$CONF_DIR/profiles"
POLICIES_DIR="$CONF_DIR/policies"
BRANCH_ROOT="/var/lib/puzzled/branches"
WAL_DIR="/var/lib/puzzled/branches/wal"
AUDIT_DIR="/var/lib/puzzled/audit"
RUNTIME_DIR="/run/puzzled"
LOG_FILE="/var/log/puzzled.log"
PID_FILE="$RUNTIME_DIR/puzzled.pid"

# ─── Helpers ─────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
fail() { echo -e "  ${RED}✗${NC} $1"; }
warn() { echo -e "  ${YELLOW}!${NC} $1"; }
info() { echo -e "  ${DIM}▸${NC} $1"; }

die() { fail "$1"; exit 1; }

check_root() {
    [ "$(id -u)" -eq 0 ] || die "Must run as root (sudo)"
}

check_linux() {
    [ "$(uname -s)" = "Linux" ] || die "Must run on Linux (use Lima VM on macOS)"
}

is_running() {
    [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null
}

# ─── Commands ────────────────────────────────────────────────────────────────

cmd_setup() {
    echo -e "${BOLD}Setting up puzzled development environment...${NC}"
    echo ""

    # Create directories
    info "Creating directories..."
    mkdir -p "$CONF_DIR" "$PROFILES_DIR" "$POLICIES_DIR"
    mkdir -p "$BRANCH_ROOT" "$WAL_DIR" "$AUDIT_DIR"
    mkdir -p "$RUNTIME_DIR"
    mkdir -p /var/lib/puzzled/manifests
    ok "Directories created"

    # Copy profiles
    if [ -d "$REPO_DIR/policies/profiles" ]; then
        cp -v "$REPO_DIR/policies/profiles/"*.yaml "$PROFILES_DIR/" 2>/dev/null || true
        ok "Profiles installed to $PROFILES_DIR"
    else
        warn "No profiles found at $REPO_DIR/policies/profiles/"
    fi

    # Copy policies
    if [ -d "$REPO_DIR/policies/rules" ]; then
        cp -v "$REPO_DIR/policies/rules/"*.rego "$POLICIES_DIR/" 2>/dev/null || true
        ok "Policies installed to $POLICIES_DIR"
    else
        warn "No policies found at $REPO_DIR/policies/rules/"
    fi

    # Write dev config (uses session bus for easier dev, relaxed settings)
    if [ ! -f "$CONF_FILE" ]; then
        cat > "$CONF_FILE" << 'CONF'
# puzzled development configuration
# Generated by dev-setup.sh

# Storage
branch_root: /var/lib/puzzled/branches
profiles_dir: /etc/puzzled/profiles
policies_dir: /etc/puzzled/policies
runtime_dir: /run/puzzled

# D-Bus: use system bus (D-Bus policy installed by Lima provisioning)
bus_type: system

# Filesystem: auto-detect (ext4 on most Lima VMs, xfs if available)
fs_type: ext4

# Limits
max_branches: 64
default_storage_quota_mb: 1024
default_inode_quota: 10000
default_lifetime_minutes: 60

# Logging
log_level: debug

# Watchdog (disabled for dev — no systemd watchdog)
watchdog_timeout_secs: 0

# Commit
commit_timeout_seconds: 300
default_action: rollback
default_profile: restricted

# Governance
require_human_approval: false
governance_review_timeout_seconds: 3600

# Don't require optional subsystems for dev
require_policies: false
require_ima: false
require_self_hardening: false

# Governance policy
governance:
  evaluation_timeout_ms: 5000
  require_signature: false

# Network proxy
network:
  proxy_listen_addr: "10.200.0.1"
  proxy_port: 3128

# Audit
audit:
  audit_log_path: /var/lib/puzzled/audit/audit.log
  retention_days: 90

# Fanotify
fanotify:
  enable: true
  mass_delete_threshold: 50

# BPF LSM (may not be available on all kernels)
bpf_lsm:
  enable: true
  max_exec_rate: 100
  max_exec_burst: 200
CONF
        ok "Config written to $CONF_FILE"
    else
        warn "Config already exists at $CONF_FILE (not overwriting)"
    fi

    # Check D-Bus policy
    DBUS_POLICY="/etc/dbus-1/system.d/org.lobstertrap.PuzzlePod1.conf"
    if [ -f "$DBUS_POLICY" ]; then
        ok "D-Bus policy exists at $DBUS_POLICY"
    else
        warn "D-Bus policy not found — creating it"
        cat > "$DBUS_POLICY" << 'DBUS'
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy user="root">
    <allow own="org.lobstertrap.PuzzlePod1"/>
    <allow send_destination="org.lobstertrap.PuzzlePod1"/>
    <allow receive_sender="org.lobstertrap.PuzzlePod1"/>
  </policy>
  <policy context="default">
    <allow send_destination="org.lobstertrap.PuzzlePod1"/>
    <allow receive_sender="org.lobstertrap.PuzzlePod1"/>
  </policy>
</busconfig>
DBUS
        systemctl reload dbus 2>/dev/null || true
        ok "D-Bus policy installed"
    fi

    # Detect filesystem type
    FS_TYPE=$(df -T "$BRANCH_ROOT" 2>/dev/null | tail -1 | awk '{print $2}')
    if [ "$FS_TYPE" = "xfs" ]; then
        ok "Branch root is on XFS (project quotas available)"
    elif [ "$FS_TYPE" = "ext4" ]; then
        ok "Branch root is on ext4"
        info "XFS project quotas not available — storage quotas will be advisory"
    elif [ "$FS_TYPE" = "virtiofs" ] || [ "$FS_TYPE" = "9p" ]; then
        warn "Branch root is on $FS_TYPE (Lima shared mount)"
        warn "OverlayFS may not work on shared mounts. Consider using a local path."
        info "Updating config to use /var/lib/puzzled/branches (local filesystem)..."
    else
        info "Branch root filesystem: $FS_TYPE"
    fi

    # Verify kernel features
    echo ""
    info "Checking kernel features..."

    # Landlock
    if [ -f /sys/kernel/security/landlock/abi_version ]; then
        ok "Landlock ABI v$(cat /sys/kernel/security/landlock/abi_version)"
    else
        warn "Landlock not available (some security tests will skip)"
    fi

    # cgroups v2
    if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
        ok "cgroups v2 unified hierarchy"
    else
        warn "cgroups v2 not detected"
    fi

    # OverlayFS
    if grep -q overlay /proc/filesystems 2>/dev/null; then
        ok "OverlayFS available"
    else
        modprobe overlay 2>/dev/null && ok "OverlayFS loaded" || warn "OverlayFS not available"
    fi

    # BPF LSM
    if [ -f /sys/kernel/security/lsm ] && grep -q bpf /sys/kernel/security/lsm; then
        ok "BPF LSM active"
    else
        warn "BPF LSM not active (exec rate limiting will be degraded)"
    fi

    # Namespaces
    if unshare --pid --fork true 2>/dev/null; then
        ok "PID namespaces available"
    else
        warn "PID namespaces not available"
    fi

    echo ""
    ok "Setup complete"
    echo ""
    info "Next steps:"
    info "  1. Build:  sudo cargo build --workspace --release"
    info "  2. Start:  sudo scripts/dev-setup.sh start"
    info "  3. Test:   sudo scripts/dev-setup.sh status"
    info ""
    info "Then in another terminal:"
    info "  mkdir -p /tmp/test"
    info "  sudo $PUZZLECTL_BIN branch create --profile=restricted --base=/tmp/test --command='[\"/bin/sleep\",\"300\"]'"
    info "  sudo $PUZZLECTL_BIN branch list"
}

cmd_build() {
    echo -e "${BOLD}Building workspace (release)...${NC}"
    echo ""

    cd "$REPO_DIR"

    # Try to use the user's cargo if available, fall back to system cargo
    if [ -f /usr/local/bin/cargo ]; then
        /usr/local/bin/cargo build --workspace --release
    elif [ -f /root/.cargo/bin/cargo ]; then
        /root/.cargo/bin/cargo build --workspace --release
    else
        cargo build --workspace --release
    fi

    ok "Build complete"

    # Verify binaries
    [ -x "$PUZZLED_BIN" ] && ok "puzzled: $PUZZLED_BIN" || fail "puzzled not found"
    [ -x "$PUZZLECTL_BIN" ] && ok "puzzlectl: $PUZZLECTL_BIN" || fail "puzzlectl not found"
}

cmd_start() {
    echo -e "${BOLD}Starting puzzled (foreground)...${NC}"
    echo ""

    [ -x "$PUZZLED_BIN" ] || die "puzzled not built. Run: sudo cargo build --workspace --release"
    is_running && die "puzzled already running (PID $(cat "$PID_FILE")). Stop it first."

    info "Config: $CONF_FILE"
    info "Branch root: $BRANCH_ROOT"
    info "Runtime: $RUNTIME_DIR"
    info "Press Ctrl+C to stop"
    echo ""

    # Run in foreground with debug logging
    RUST_LOG=puzzled=debug exec "$PUZZLED_BIN"
}

cmd_startbg() {
    echo -e "${BOLD}Starting puzzled (background)...${NC}"
    echo ""

    [ -x "$PUZZLED_BIN" ] || die "puzzled not built. Run: sudo cargo build --workspace --release"
    is_running && die "puzzled already running (PID $(cat "$PID_FILE"))"

    RUST_LOG=puzzled=debug nohup "$PUZZLED_BIN" >> "$LOG_FILE" 2>&1 &
    local pid=$!
    echo "$pid" > "$PID_FILE"

    # Wait a moment and check it's still running
    sleep 1
    if kill -0 "$pid" 2>/dev/null; then
        ok "puzzled started (PID $pid)"
        info "Log: tail -f $LOG_FILE"
        info "Stop: sudo scripts/dev-setup.sh stop"
    else
        fail "puzzled exited immediately — check $LOG_FILE"
        tail -20 "$LOG_FILE" 2>/dev/null || true
        exit 1
    fi
}

cmd_stop() {
    if is_running; then
        local pid
        pid=$(cat "$PID_FILE")
        echo -e "${BOLD}Stopping puzzled (PID $pid)...${NC}"
        kill "$pid"

        # Wait up to 5 seconds for graceful shutdown
        for i in $(seq 1 10); do
            if ! kill -0 "$pid" 2>/dev/null; then
                rm -f "$PID_FILE"
                ok "puzzled stopped"
                return 0
            fi
            sleep 0.5
        done

        warn "puzzled didn't stop gracefully, sending SIGKILL"
        kill -9 "$pid" 2>/dev/null || true
        rm -f "$PID_FILE"
        ok "puzzled killed"
    else
        info "puzzled is not running"
        rm -f "$PID_FILE" 2>/dev/null || true
    fi
}

cmd_status() {
    echo -e "${BOLD}puzzled status:${NC}"
    echo ""

    if is_running; then
        local pid
        pid=$(cat "$PID_FILE")
        ok "Running (PID $pid)"
        info "Uptime: $(ps -o etime= -p "$pid" 2>/dev/null | tr -d ' ')"
        info "Memory: $(ps -o rss= -p "$pid" 2>/dev/null | awk '{printf "%.1f MB", $1/1024}' 2>/dev/null)"
    else
        info "Not running"
    fi

    echo ""

    # Check D-Bus
    if command -v busctl &>/dev/null; then
        if busctl --system list 2>/dev/null | grep -q "org.lobstertrap.PuzzlePod1.Manager"; then
            ok "D-Bus service registered"
        else
            info "D-Bus service not registered (puzzled not running or using session bus)"
        fi
    fi

    # Check branches
    if [ -x "$PUZZLECTL_BIN" ] && is_running; then
        echo ""
        info "Branches:"
        "$PUZZLECTL_BIN" branch list 2>/dev/null || info "  (none or D-Bus not available)"
    fi

    # Show config
    echo ""
    info "Config: $CONF_FILE"
    info "Branch root: $BRANCH_ROOT"
    info "Runtime: $RUNTIME_DIR"
    info "Log: $LOG_FILE"
}

cmd_logs() {
    if [ -f "$LOG_FILE" ]; then
        tail -f "$LOG_FILE"
    else
        info "No log file at $LOG_FILE (puzzled may not have started yet)"
    fi
}

cmd_clean() {
    echo -e "${BOLD}Cleaning runtime state...${NC}"
    echo ""

    if is_running; then
        die "puzzled is still running. Stop it first: sudo scripts/dev-setup.sh stop"
    fi

    # Unmount any leftover OverlayFS mounts
    for mount in $(mount | grep "$BRANCH_ROOT" | awk '{print $3}'); do
        umount "$mount" 2>/dev/null && info "Unmounted $mount" || true
    done

    rm -rf "$BRANCH_ROOT"/*
    rm -rf "$RUNTIME_DIR"/*
    rm -f "$LOG_FILE"
    ok "Cleaned: $BRANCH_ROOT"
    ok "Cleaned: $RUNTIME_DIR"
    ok "Cleaned: $LOG_FILE"

    # Recreate essential dirs
    mkdir -p "$BRANCH_ROOT" "$WAL_DIR" "$RUNTIME_DIR"
    ok "Recreated empty directories"
}

cmd_all() {
    cmd_setup
    echo ""
    cmd_build
    echo ""
    cmd_start
}

# ─── Main ────────────────────────────────────────────────────────────────────

check_root
check_linux

case "${1:-}" in
    setup)    cmd_setup ;;
    build)    cmd_build ;;
    start)    cmd_start ;;
    startbg)  cmd_startbg ;;
    stop)     cmd_stop ;;
    status)   cmd_status ;;
    logs)     cmd_logs ;;
    clean)    cmd_clean ;;
    all)      cmd_all ;;
    *)
        echo -e "${BOLD}dev-setup.sh${NC} — puzzled development environment"
        echo ""
        echo "Usage: sudo scripts/dev-setup.sh <command>"
        echo ""
        echo "Commands:"
        echo "  setup     Create dirs, install config/profiles/policies"
        echo "  build     Build workspace in release mode"
        echo "  start     Start puzzled in foreground (Ctrl+C to stop)"
        echo "  startbg   Start puzzled in background"
        echo "  stop      Stop background puzzled"
        echo "  status    Check if puzzled is running"
        echo "  logs      Tail puzzled log (background mode)"
        echo "  clean     Remove all runtime state"
        echo "  all       setup + build + start"
        echo ""
        echo "Quick start:"
        echo "  sudo scripts/dev-setup.sh setup"
        echo "  sudo cargo build --workspace --release"
        echo "  sudo scripts/dev-setup.sh start"
        echo ""
        echo "Then in another terminal:"
        echo "  mkdir -p /tmp/test"
        echo "  sudo $PUZZLECTL_BIN branch create --profile=restricted --base=/tmp/test --command='[\"/bin/sleep\",\"300\"]'"
        echo "  sudo $PUZZLECTL_BIN branch list"
        exit 1
        ;;
esac
