#!/bin/bash
# dev-setup-user.sh — Set up and run puzzled in user mode (no root required)
#
# Usage:
#   scripts/dev-setup-user.sh setup     # Create user dirs, install config/profiles/policies
#   scripts/dev-setup-user.sh start     # Start puzzled on session bus in foreground
#   scripts/dev-setup-user.sh startbg   # Start puzzled on session bus in background
#   scripts/dev-setup-user.sh stop      # Stop background puzzled
#   scripts/dev-setup-user.sh status    # Check if puzzled is running
#   scripts/dev-setup-user.sh clean     # Remove all user-mode puzzled state
#   scripts/dev-setup-user.sh all       # setup + start in foreground
#
# Prerequisites:
#   - Linux (Fedora 42+ / RHEL 10+)
#   - Rust toolchain installed (cargo build --workspace --release completed)
#   - Do NOT run as root

set -euo pipefail
umask 077

# ─── Configuration ───────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Binaries (release build)
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-/var/tmp/puzzlepod-target}"
PUZZLED_BIN="$CARGO_TARGET_DIR/release/puzzled"
[ -x "$PUZZLED_BIN" ] || PUZZLED_BIN="$REPO_DIR/target/release/puzzled"
PUZZLECTL_BIN="$CARGO_TARGET_DIR/release/puzzlectl"
[ -x "$PUZZLECTL_BIN" ] || PUZZLECTL_BIN="$REPO_DIR/target/release/puzzlectl"

# User-mode directories (XDG-compliant)
CONF_DIR="$HOME/.config/puzzled"
CONF_FILE="$CONF_DIR/puzzled.conf"
PROFILES_DIR="$CONF_DIR/profiles"
POLICIES_DIR="$CONF_DIR/policies"
BRANCH_ROOT="$HOME/.local/share/puzzled/branches"
AUDIT_DIR="$HOME/.local/share/puzzled/audit"
TRUST_DIR="$HOME/.local/share/puzzled/trust"
PROVENANCE_DIR="$HOME/.local/share/puzzled/provenance"
RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/puzzled"
PID_FILE="$RUNTIME_DIR/puzzled.pid"
LOG_FILE="$RUNTIME_DIR/puzzled.log"

# ─── Helpers ─────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
fail() { echo -e "  ${RED}✗${NC} $1"; }
warn() { echo -e "  ${YELLOW}!${NC} $1"; }
info() { echo -e "  ${DIM}▸${NC} $1"; }

die() { fail "$1"; exit 1; }

check_not_root() {
    [ "$(id -u)" -ne 0 ] || die "Do NOT run as root — this is the user-mode setup script"
}

check_linux() {
    [ "$(uname -s)" = "Linux" ] || die "Must run on Linux"
}

is_running() {
    if [ ! -f "$PID_FILE" ]; then
        return 1
    fi
    local pid
    pid=$(cat "$PID_FILE")
    # Validate PID is a positive integer
    if ! [[ "$pid" =~ ^[0-9]+$ ]] || [ "$pid" -le 1 ]; then
        return 1
    fi
    # Verify the PID belongs to an puzzled process
    if [ -f "/proc/$pid/comm" ]; then
        grep -q puzzled "/proc/$pid/comm" 2>/dev/null || return 1
    else
        kill -0 "$pid" 2>/dev/null || return 1
    fi
}

# ─── Commands ────────────────────────────────────────────────────────────────

cmd_setup() {
    echo -e "${BOLD}Setting up puzzled user-mode environment...${NC}"
    echo ""

    # Create directories
    info "Creating user directories..."
    mkdir -p "$CONF_DIR" "$PROFILES_DIR" "$POLICIES_DIR"
    mkdir -p "$BRANCH_ROOT"
    mkdir -p "$AUDIT_DIR"
    mkdir -p "$TRUST_DIR" "$PROVENANCE_DIR"
    mkdir -p "$RUNTIME_DIR"
    ok "Directories created"

    # Copy profiles
    if [ -d "$REPO_DIR/policies/profiles" ] && compgen -G "$REPO_DIR/policies/profiles/*.yaml" > /dev/null 2>&1; then
        cp "$REPO_DIR/policies/profiles/"*.yaml "$PROFILES_DIR/"
        ok "Profiles installed to $PROFILES_DIR"
    else
        warn "No .yaml profiles found in $REPO_DIR/policies/profiles/"
    fi

    # Copy policies
    if [ -d "$REPO_DIR/policies/rules" ] && compgen -G "$REPO_DIR/policies/rules/*.rego" > /dev/null 2>&1; then
        cp "$REPO_DIR/policies/rules/"*.rego "$POLICIES_DIR/"
        ok "Policies installed to $POLICIES_DIR"
    else
        warn "No .rego policies found in $REPO_DIR/policies/rules/"
    fi

    # Validate $HOME does not contain YAML metacharacters that would break
    # the generated config (e.g., colons, quotes, braces).
    if [[ "$HOME" =~ [\:\"\'\{\}\[\]\#\&\*\!\|\>\,\?] ]]; then
        die "\$HOME contains YAML metacharacters ('$HOME') — cannot generate safe config. Use --config with a manually written config file."
    fi

    # Write user-mode config
    if [ ! -f "$CONF_FILE" ]; then
        cat > "$CONF_FILE" << CONF
# puzzled user-mode configuration
# Generated by dev-setup-user.sh
#
# WARNING: Development configuration — NOT for production use.
# require_policies, require_ima, and require_self_hardening are disabled.

# Storage (user-mode paths)
branch_root: "${BRANCH_ROOT}"
profiles_dir: "${PROFILES_DIR}"
policies_dir: "${POLICIES_DIR}"
runtime_dir: "${RUNTIME_DIR}"

# D-Bus: session bus (no root required)
bus_type: session

# Filesystem: ext4 (no XFS project quotas in user mode)
fs_type: ext4

# Limits (lower for user sessions)
max_branches: 16
default_storage_quota_mb: 512
default_inode_quota: 5000
default_lifetime_minutes: 60

# Logging
log_level: debug
log_target: stderr

# Watchdog (disabled for dev)
watchdog_timeout_secs: 0

# Commit
commit_timeout_seconds: 300
default_action: rollback
default_profile: restricted

# Governance
require_human_approval: false
governance_review_timeout_seconds: 3600

# Don't require optional subsystems
require_policies: false
require_ima: false
require_self_hardening: false

# Governance policy
governance:
  evaluation_timeout_ms: 5000
  require_signature: false

# Audit (user-mode paths)
audit:
  audit_log_path: "${AUDIT_DIR}/audit.log"
  integrity_key_path: "${AUDIT_DIR}/.hmac_key"
  retention_days: 90

# Signing key (user-mode path)
signing_key_path: "${CONF_DIR}/signing-key.pem"

# Socket and PID file
socket_path: "${RUNTIME_DIR}/puzzled.sock"
pid_file: "${PID_FILE}"

# Fanotify: disabled in user mode (requires CAP_SYS_ADMIN for FAN_REPORT_FID)
fanotify:
  enable: false

# BPF LSM: disabled in user mode (requires CAP_BPF)
bpf_lsm:
  enable: false
CONF
        ok "Config written to $CONF_FILE"
    else
        warn "Config already exists at $CONF_FILE (not overwriting)"
    fi

    # Check D-Bus session bus
    if [ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
        ok "D-Bus session bus: $DBUS_SESSION_BUS_ADDRESS"
    else
        warn "DBUS_SESSION_BUS_ADDRESS not set"
        info "If running via SSH, use: dbus-run-session -- scripts/dev-setup-user.sh start"
    fi

    # Check kernel features relevant to user mode
    echo ""
    info "Checking kernel features (user-mode relevant)..."

    if [ -f /sys/kernel/security/landlock/abi_version ]; then
        ok "Landlock ABI v$(cat /sys/kernel/security/landlock/abi_version) (works unprivileged)"
    else
        warn "Landlock not available"
    fi

    if command -v fuse-overlayfs &>/dev/null; then
        ok "fuse-overlayfs available ($(fuse-overlayfs --version 2>&1 | head -1))"
    else
        warn "fuse-overlayfs not found — install with: dnf install fuse-overlayfs"
    fi

    if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
        ok "cgroups v2 unified hierarchy"
    else
        warn "cgroups v2 not detected"
    fi

    echo ""
    ok "User-mode setup complete"
    echo ""
    info "Next steps:"
    info "  1. Build:  cargo build --workspace --release"
    info "  2. Start:  scripts/dev-setup-user.sh start"
    info "  3. Status: scripts/dev-setup-user.sh status"
    info ""
    info "Then in another terminal:"
    info "  $PUZZLECTL_BIN --bus session branch list"
}

cmd_start() {
    echo -e "${BOLD}Starting puzzled (user mode, session bus)...${NC}"
    echo ""

    if is_running; then
        warn "puzzled already running (PID $(cat "$PID_FILE"))"
        return 0
    fi

    if [ ! -x "$PUZZLED_BIN" ]; then
        die "puzzled binary not found at $PUZZLED_BIN — run: cargo build --workspace --release"
    fi

    mkdir -p "$RUNTIME_DIR"

    info "Binary: $PUZZLED_BIN"
    info "Config: $CONF_FILE"
    info "Bus:    session"
    echo ""

    # Write PID file before exec so cmd_stop can find the process.
    # The trap removes it if exec fails; on success, puzzled replaces this
    # process and the PID file is cleaned up by cmd_stop or cmd_clean.
    echo "$$" > "$PID_FILE"
    trap 'rm -f "$PID_FILE"' EXIT
    exec env RUST_LOG=puzzled=debug "$PUZZLED_BIN" --config "$CONF_FILE"
}

cmd_startbg() {
    echo -e "${BOLD}Starting puzzled in background (user mode)...${NC}"

    if is_running; then
        warn "puzzled already running (PID $(cat "$PID_FILE"))"
        return 0
    fi

    if [ ! -x "$PUZZLED_BIN" ]; then
        die "puzzled binary not found at $PUZZLED_BIN — run: cargo build --workspace --release"
    fi

    mkdir -p "$RUNTIME_DIR"

    env RUST_LOG=puzzled=debug "$PUZZLED_BIN" --config "$CONF_FILE" > "$LOG_FILE" 2>&1 &
    local pid=$!
    echo "$pid" > "$PID_FILE"

    sleep 1
    if kill -0 "$pid" 2>/dev/null \
        && [ -f "/proc/$pid/comm" ] && grep -q puzzled "/proc/$pid/comm" 2>/dev/null; then
        ok "puzzled started (PID $pid)"
        info "Log: $LOG_FILE"
    else
        rm -f "$PID_FILE"
        fail "puzzled failed to start — check $LOG_FILE"
        return 1
    fi
}

cmd_stop() {
    if [ -f "$PID_FILE" ]; then
        local pid
        pid=$(cat "$PID_FILE")
        # Validate PID and verify it belongs to puzzled before signaling
        if [[ "$pid" =~ ^[0-9]+$ ]] && [ "$pid" -gt 1 ] \
            && kill -0 "$pid" 2>/dev/null \
            && [ -f "/proc/$pid/comm" ] && grep -q puzzled "/proc/$pid/comm" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            # Wait for process to exit (up to 5 seconds)
            local i=0
            while kill -0 "$pid" 2>/dev/null && [ $i -lt 10 ]; do
                sleep 0.5
                i=$((i + 1))
            done
            if kill -0 "$pid" 2>/dev/null; then
                warn "puzzled (PID $pid) did not exit cleanly, sending SIGKILL"
                kill -9 "$pid" 2>/dev/null || true
            fi
            ok "puzzled stopped (was PID $pid)"
        else
            info "puzzled is not running (stale PID file)"
        fi
        rm -f "$PID_FILE"
    else
        info "puzzled is not running"
    fi
}

cmd_status() {
    if is_running; then
        ok "puzzled running (PID $(cat "$PID_FILE"))"
        if [ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
            info "D-Bus: $DBUS_SESSION_BUS_ADDRESS"
            busctl --user list 2>/dev/null | grep -i agent || info "(puzzled name not yet visible on bus)"
        fi
    else
        info "puzzled is not running"
    fi
}

cmd_clean() {
    echo -e "${BOLD}Cleaning user-mode puzzled state...${NC}"

    cmd_stop 2>/dev/null || true

    # Unmount any active fuse-overlayfs mounts before removing branches
    local mp
    for mp in "$BRANCH_ROOT"/*/merged; do
        if [ -d "$mp" ] && mountpoint -q "$mp" 2>/dev/null; then
            fusermount3 -u "$mp" 2>/dev/null \
                || fusermount -u "$mp" 2>/dev/null \
                || warn "Failed to unmount $mp — manual cleanup may be needed"
        fi
    done

    rm -rf "$BRANCH_ROOT"
    rm -rf "$AUDIT_DIR"
    rm -rf "$TRUST_DIR" "$PROVENANCE_DIR"
    rm -rf "$RUNTIME_DIR"
    ok "Runtime state cleaned"

    info "Config preserved at $CONF_DIR (use 'rm -rf $CONF_DIR' to remove)"
}

# ─── Main ────────────────────────────────────────────────────────────────────

check_not_root
check_linux

case "${1:-}" in
    setup)    cmd_setup ;;
    start)    cmd_start ;;
    startbg)  cmd_startbg ;;
    stop)     cmd_stop ;;
    status)   cmd_status ;;
    clean)    cmd_clean ;;
    all)      cmd_setup; echo ""; cmd_start ;;
    *)
        echo "Usage: $(basename "$0") {setup|start|startbg|stop|status|clean|all}"
        echo ""
        echo "User-mode puzzled setup (no root required)."
        echo ""
        echo "Commands:"
        echo "  setup    Create user dirs, install config/profiles/policies"
        echo "  start    Start puzzled on session bus (foreground)"
        echo "  startbg  Start puzzled on session bus (background)"
        echo "  stop     Stop background puzzled"
        echo "  status   Check if puzzled is running"
        echo "  clean    Remove all runtime state"
        echo "  all      setup + start (foreground)"
        exit 1
        ;;
esac
